services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: linode_dereck-redis
    volumes:
      - redis-data:/data
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--appendonly',
        'yes'
      ]
    networks:
      - dereck-network

networks:
  dereck-network:
    external: true

volumes:
  redis-data:
    name: dereck-redis-data
    driver: local
