name: Release Prod Docker image to Linode

on:
  release:
    types: [published]
jobs:
  deploy_to_linode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" > .env

      - name: Copy files to Linode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: './docker-compose.yml, .env'
          target: '/root/docker-compose-redis/'

      - name: Execute remote Docker Compose command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /root/docker-compose-redis/
            docker compose --env-file .env pull
            docker compose --env-file .env down
            docker container prune -f
            docker image prune -f
            docker compose --env-file .env up -d
